-- Better Auth core tables (generated by `npx auth@1.7.2 generate` for sqlite; account.issuer is new in 1.7)
CREATE TABLE IF NOT EXISTS "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null);
CREATE TABLE IF NOT EXISTS "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "account" ("id" text not null primary key, "issuer" text not null, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);
CREATE TABLE IF NOT EXISTS "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);
CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");
CREATE UNIQUE INDEX IF NOT EXISTS "account_issuer_accountId_uidx" ON "account" ("issuer", "accountId");

-- Recipes: one shared household box
CREATE TABLE IF NOT EXISTS recipes (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  platform TEXT NOT NULL,
  title TEXT,
  creator TEXT,
  thumbnail TEXT,
  caption TEXT,
  transcript TEXT,
  cuisine TEXT,
  category TEXT,
  summary TEXT,
  ingredients TEXT,
  steps TEXT,
  tags TEXT,
  servings TEXT,
  total_minutes INTEGER,
  status TEXT NOT NULL DEFAULT 'pending',
  source TEXT,
  confidence REAL,
  saved_by TEXT REFERENCES "user"("id") ON DELETE SET NULL,
  requested_by TEXT REFERENCES "user"("id") ON DELETE SET NULL,   -- "please cook this for me"
  requested_at TEXT,
  favorite INTEGER NOT NULL DEFAULT 0,
  cooked INTEGER NOT NULL DEFAULT 0,
  cooked_by TEXT REFERENCES "user"("id") ON DELETE SET NULL,
  cooked_at TEXT,
  note TEXT,
  error TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_recipes_cuisine ON recipes(cuisine);
CREATE INDEX IF NOT EXISTS idx_recipes_status ON recipes(status);
CREATE INDEX IF NOT EXISTS idx_recipes_requested ON recipes(requested_by);
